/**
 * they are used to represent business concepts and define business logic and behavior in the application.
 */
package com.adminparq.adminparq.infrastructure.db.springdata.dbo;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA notation used to indicate that the annotated class is a JPA entity class.
 */
@Entity

/*
 * Provided by JPA to specify more details about the table associated with the class.
 */
@Table(name = "employee")

@Getter
@Setter
@NoArgsConstructor

public class EmployeeEntity {

    /**
     * It is used to link the annotated field to the primary key column.
     */
    @Id

    /*
     * Defines the primary key generation strategy. IDENTITY
     * means that the primary key values will be generated by an auto-incrementing field.
     */
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    /*
     * specify basic persistence of a property or field of an entity
     */
    @Basic(optional = false)

    /*
     * It's a JPA annotation that we use to define some details about the mapped column.
     */
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "name")
    private String name;

    @Column(name = "user")
    private String user;

    @Column(name = "password")
    private String password;

}

